# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
commands:
  sayhello:
    description:  "A very simple command for demo"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      -run: echo << parameters.to >>
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
defaults: &dockers
  docker:
        - image: circleci/node:13.8.0
jobs:
  print_hello:
    <<: *dockers
    steps:
      - run: echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt            
  print_world:
    <<: *dockers
    steps:
      - sayhello:
          to: "KAPIL"
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - print_hello
      - print_world:
          requires:
            - print_hello